cache:
    - 'C:\Users\appveyor\.cargo'

install:
    - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-gnu.exe'
    - rust-nightly-x86_64-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
    - SET PATH=%PATH%;C:\Program Files\Rust\bin;C:\msys64\mingw64\bin
    - rustc -V
    - cargo -V

build: false

test_script:
    - cargo build
    - cargo test
