[package]

name = "euler"
version = "0.0.1"
authors = ["Zbigniew Siciarz <zbigniew@siciarz.net>"]

[dependencies]
getopts = "~0.2.9"
num = "~0.1.22"

[dependencies.slow_primes]
git = "https://github.com/huonw/slow_primes.git"
