[package]

name = "euler"
version = "0.0.1"
authors = ["Zbigniew Siciarz <zbigniew@siciarz.net>"]

[[bin]]

name = "euler"
path = "src/main.rs"

[dependencies.slow_primes]

git = "https://github.com/huonw/slow_primes.git"

[dependencies.num]

git = "https://github.com/rust-lang/num"
